### ISSUE TITLE
Looking Forward

### ISSUE THREAD

**Issue by RetroFlix** [ChoccyHobNob/Pie-Assist#1]
Looking forward to what this will do.   i failed 4 times and finally succeeded at compiling mame on Raspberry Pi via the tutorial on your website.  it was the best and apparently only working tutorial on the subject.
so thanks for that.

anyway why im writing this is to ask what happened to your Cygnus theme on RetroPie???   i just got another pi after not having one and disappointed i cant find my 2nd favorite theme.  (1.Tronkyfran, 2.Cygnus, 3.Magazine Madness)

and now also a bit curious as to what this script will do exactly.. you didn't specify, lol.

**Comment by ChoccyHobNob** [comment]
I took the cygnus theme down after the Retropie devs banned me on the official forums and blocked me on github, twice. Great project, shitty devs.
